"""Image fact-check handler -- orchestrates OCR, AI detection, and text fact-checking."""

from __future__ import annotations

import asyncio

from app.engines.hive_detector import detect_ai_image
from app.engines.ocr import extract_text_from_image, extract_labels_from_image
from app.engines.text_handler import fact_check_text
from app.engines.verdict_engine import Verdict
from app.verdict.confidence import VerdictLabel
from app.utils.logger import get_logger

logger = get_logger("engines.image")


async def fact_check_image(image_bytes: bytes, caption: str = "") -> str:
    """Full image fact-checking pipeline.

    1. Run OCR + AI detection + label detection in parallel
    2. If AI-generated, report that immediately
    3. If text found (OCR or caption), run through text fact-check pipeline
    4. Combine results
    """
    ocr_task = extract_text_from_image(image_bytes)
    ai_task = detect_ai_image(image_bytes)
    label_task = extract_labels_from_image(image_bytes)

    ocr_text, ai_result, labels = await asyncio.gather(
        ocr_task, ai_task, label_task
    )

    parts: list[str] = []

    if ai_result.is_ai_generated:
        confidence_pct = int(ai_result.ai_confidence * 100)
        parts.append(f"🤖 *AI-GENERATED IMAGE DETECTED*")
        parts.append("")
        parts.append(
            f"This image appears to be AI-generated "
            f"({confidence_pct}% confidence)."
        )
        if ai_result.model_detected:
            parts.append(f"Likely generated by: _{ai_result.model_detected}_")
        if ai_result.is_deepfake:
            deepfake_pct = int(ai_result.deepfake_confidence * 100)
            parts.append("")
            parts.append(
                f"⚠️ *Deepfake detected* ({deepfake_pct}% confidence). "
                "This image may contain manipulated faces."
            )
        parts.append("")
        parts.append(
            "💡 _AI-generated images can be used to spread misinformation. "
            "Always verify the source before sharing._"
        )

    combined_text = ""
    if caption:
        combined_text = caption
    if ocr_text:
        combined_text = f"{combined_text}\n{ocr_text}".strip() if combined_text else ocr_text

    if combined_text:
        if parts:
            parts.append("")
            parts.append("---")
            parts.append("")
            parts.append("📝 *Text found in image — checking claims:*")
            parts.append("")

        text_message, _ = await fact_check_text(combined_text)
        parts.append(text_message)
    elif not parts:
        label_desc = ", ".join(labels[:5]) if labels else "no identifiable objects"
        parts.append(
            f"🖼️ I analyzed this image and found: _{label_desc}_\n\n"
            "I didn't find any text or specific claims to fact-check. "
            "If there's a claim about this image, try sending it as text and I'll check it!"
        )

    return "\n".join(parts)
