"""Video fact-check handler -- Hive deepfake/AI detection + GPT-4o frame analysis."""

from __future__ import annotations

import asyncio
import base64

from openai import AsyncOpenAI

from app.config import OPENAI_API_KEY, OPENAI_MODEL
from app.engines.hive_detector import detect_ai_video
from app.engines.text_handler import fact_check_text
from app.utils.logger import get_logger

logger = get_logger("engines.video")

_client = AsyncOpenAI(api_key=OPENAI_API_KEY)

MAX_VIDEO_SIZE = 20 * 1024 * 1024  # 20MB limit for Hive


async def fact_check_video(video_bytes: bytes, caption: str = "") -> str:
    """Full video fact-checking pipeline.

    1. Run Hive AI/deepfake detection
    2. If caption provided, fact-check the text claims
    3. Combine results
    """
    if len(video_bytes) > MAX_VIDEO_SIZE:
        return (
            "📹 This video is too large for me to analyze (max 20MB). "
            "Try sending a shorter clip, or describe the claim in the video as text "
            "and I'll fact-check that!"
        )

    ai_task = detect_ai_video(video_bytes)

    caption_task = None
    if caption:
        caption_task = fact_check_text(caption)

    ai_result = await ai_task

    parts: list[str] = []

    if ai_result.is_ai_generated:
        confidence_pct = int(ai_result.ai_confidence * 100)
        parts.append("🤖 *AI-GENERATED VIDEO DETECTED*")
        parts.append("")
        parts.append(
            f"This video appears to be AI-generated "
            f"({confidence_pct}% confidence)."
        )
        if ai_result.model_detected:
            parts.append(f"Likely generated by: _{ai_result.model_detected}_")

    if ai_result.is_deepfake:
        deepfake_pct = int(ai_result.deepfake_confidence * 100)
        if not ai_result.is_ai_generated:
            parts.append("⚠️ *DEEPFAKE VIDEO DETECTED*")
            parts.append("")
        else:
            parts.append("")
        parts.append(
            f"⚠️ *Deepfake detected* ({deepfake_pct}% confidence). "
            "This video may contain manipulated faces or altered content."
        )

    if ai_result.is_ai_generated or ai_result.is_deepfake:
        parts.append("")
        parts.append(
            "💡 _AI-generated and deepfake videos are increasingly used to spread "
            "inaccurate content. Always verify the source before sharing._"
        )

    if caption_task:
        text_message, _ = await caption_task
        if parts:
            parts.append("")
            parts.append("---")
            parts.append("")
            parts.append("📝 *Caption claims — checking:*")
            parts.append("")
        parts.append(text_message)
    elif not parts:
        parts.append(
            "📹 I analyzed this video but couldn't detect AI generation or deepfake manipulation.\n\n"
            "If there's a specific claim in this video, try typing it out as text "
            "and I'll fact-check it for you!"
        )

    return "\n".join(parts)
